name: lawan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  intl: ^0.19.0
  wheel_picker: ^0.1.1
  image_picker: ^1.1.2
  image_picker_android: ^0.8.12+13
  image_picker_platform_interface: ^2.10.0
  firebase_core: ^2.24.2
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.8
  blur: ^4.0.0
  table_calendar: ^3.1.2
  slide_to_act:
    git: 
      url: https://github.com/2001arman/flutter-slide-to-act.git
      ref: 'master'
  video_player: ^2.9.2
  file_picker: ^8.1.3
  emoji_picker_flutter: ^3.1.0

  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1

  flutter_to_pdf: ^0.2.2
  path_provider: ^2.1.4
  syncfusion_flutter_pdfviewer: ^27.1.55
  appinio_social_share: ^0.3.2
  share_plus: ^10.1.1

  geocoding: ^3.0.0
  flutter_google_maps_webservices: ^1.1.1

  url_launcher: ^6.3.1
  add_2_calendar: ^3.0.1

  sliver_app_bar_builder: ^1.1.0

  country_state_city_pro: ^0.0.6

  expansion_widget: ^0.1.0
  dotted_border: ^2.1.0
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.3.0

dependency_overrides:

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/avatars/
    - assets/banks/
    - assets/video/
    - assets/fields/
    - assets/achievement/
    - assets/arena/

  fonts:
    - family: Lufga
      fonts:
        - asset: assets/fonts/LufgaBlack.ttf
          weight: 900
        - asset: assets/fonts/LufgaBlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/LufgaBold.ttf
          weight: 700
        - asset: assets/fonts/LufgaBoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/LufgaExtraBold.ttf
          weight: 800
        - asset: assets/fonts/LufgaExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/LufgaLightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/LufgaMedium.ttf
          weight: 500
        - asset: assets/fonts/LufgaMediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/LufgaSemiBold.ttf
          weight: 600
        - asset: assets/fonts/LufgaSemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/LufgaExtraLight.ttf
          weight: 200
        - asset: assets/fonts/LufgaExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/LufgaItalic.ttf
          style: italic
        - asset: assets/fonts/LufgaLight.ttf
          weight: 300
        - asset: assets/fonts/LufgaRegular.ttf
        - asset: assets/fonts/LufgaThin.ttf
          weight: 100
        - asset: assets/fonts/LufgaThinItalic.ttf
          weight: 100
          style: italic

